### ISSUE TITLE
[Bug]: Slash Command `baninfo` is non functioning 

### ISSUE THREAD

**Issue by werewolfboy13** [afocommunity/suggestions#1]
### What Happened?

Upon Using the `/baninfo` the command fails with the following error stack on console. 

TypeError: Cannot read property 'id' of undefined
    at WebSocketManager. (C:\Users\Administrator\Desktop\Servers\AFO-BOT-2\Examples\Logic\Discord.js:714:142)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### Project

AFO BOT 2 (Discord)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by bombitmanbomb** [comment]
Potentially fixed with werewolfboy13/AFO-BOT-2#8118fda

**Comment by werewolfboy13** [comment]
> Potentially fixed with werewolfboy13/AFO-BOT-2#8118fda
Issue is partially fixed but clan reps need access still.
