### ISSUE TITLE
[Request]: AFO Apology Enforcer

### ISSUE THREAD

**Issue by bombitmanbomb** [afocommunity/suggestions#12]
### What do you want to see

Enforce Apologies after a certain threshold is met.

After X teamkills, start an Y minute timer. If no "Apology" is said, Kick/ban said user. Warn the rule to the user shortly beforehand.

## Reason
The last week has seen 215 bans for tk/dc alone, with the total TeamKill count exceeding 8000. Measure to "Suggest" users follow the listed rules.

## Example:
Jamsheed kills 4 people over the course of an hour. The user has never said a single word in chat.
a 1 minute timer starts, after 30 seconds the user is warned the TK rule again. If nothing is said, Kick said user and tell them Why they were kicked. 
after a second offence, could be a ban 

# Affected Plugins
* AFOTeamkillDisconnect

### Project

Spaghetti (Squad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by werewolfboy13** [comment]
@bombitmanbomb 

> Sounds good. Only suggestion would be to make t only activate after multiple tk's, and not just one. Lots of people do end up apologizing in VC, even though they should be doing it in all chat. I'd say to have it trigger after 3 or 4 tk's. Consecutive and non consecutive is something to think about as well. This might already be in there, idk
