### ISSUE TITLE
[Request]: Name Validation Changes for Names less than 3

### ISSUE THREAD

**Issue by bombitmanbomb** [afocommunity/suggestions#3]
### What do you want to see

Modified Name validation for the new rule reguarding name length.

Current rule: All names must contain 3 english characters

Proposed exception:
Names of length 3 or less must ONLY contain alphanumeric characters, and the Latin Count must be greater or equal to the Number Count

Examples:

## Valid Names:
- D9
- Amy
- DUD
- W0T

## Invalid Names:
- 123
- f24
- `.A`
- .
- $u$
- よし

### Project

Spaghetti (Squad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by werewolfboy13** [comment]
https://github.com/werewolfboy13/Spaghetti-Bot/pull/24 

Attached to the above pull request.

**Comment by werewolfboy13** [comment]
@bombitmanbomb if you don't hear anything when you can do the changes that we talked about tomorrow.

**Comment by werewolfboy13** [comment]
Those changes are approved.

**Comment by bombitmanbomb** [comment]
Plugin Completed
