### ISSUE TITLE
[Feature]: Add option to specify Users with !command triggers

### ISSUE THREAD

**Issue by bombitmanbomb** [afocommunity/suggestions#31]
### Problem

!tk, !sl, etc are global warns and require warning players seperately

### Solution

add option to specify users after commands to directly warn the individuals with pre-defined messages

### Related Project

Squad Server Plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that there is No promise this feature will be added

**Comment by bombitmanbomb** [comment]
Examples: 
`!sl -w Snow BigSock 'Some long name'` -w = Warn Only. can use quotes '/" to specify explicit names with spaces in them
`!tk Hostage` Broadcast & Direct Warn a user who's name starts with `/^Hostage/i`
Potentially could have Group-Warnings: `!lock -team 1 -squad 4` might be too big-brain for some members.
Wildcards for names with symbols: `小雷 Xiao` : `!crewman '** Xiao'`

**Comment by bombitmanbomb** [comment]
Revit if new command system is added. 
Could make staff lazy.

**Comment by werewolfboy13** [comment]
This will need some fine tuning for audit logging purposes, it does not take away for a moderators/admins responsibilities from using BM for admin action logging. This also ties into #33.
