### ISSUE TITLE
[Feature]: Easier moderation system

### ISSUE THREAD

**Issue by rozzy124** [afocommunity/suggestions#33]
### Problem

Using moderator tools are slow / difficult to use. Going to the RCON, kicking, warning, banning, etc. takes forever

### Solution

Create a command where we can warn / kick people  from in the game

### Related Project

General Squad Server

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that there is No promise this feature will be added

**Comment by bombitmanbomb** [comment]
See #31 for possible flag/structure examples

**Comment by bombitmanbomb** [comment]
Pending Squad Division

**Comment by werewolfboy13** [comment]
This will need some fine tuning for audit logging purposes, it does not take away for a moderators/admins responsibilities from using BM for admin action logging. This also ties into #31.

**Comment by werewolfboy13** [comment]
Rejected in meeting 100622. It is apart of being an admin/mod. You need to be able to use the tools that we have.
