### ISSUE TITLE
[Feature]: Revive Clan Events

### ISSUE THREAD

**Issue by bombitmanbomb** [afocommunity/suggestions#36]
### Solution

Host monthly 'Ops' on a weekend once or twice a month. Small scale scenarios. Potentially with Mods?
Some Could be potentially Open, which may result in a passive-seed of a second server.
Could Occasionally set up Group-Events w/ other groups.

Winning team gets gloating privileges. 

Could encourage recording for footage for the Media Team.

### Related Project

General Squad Server

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that there is No promise this feature will be added

**Comment by bombitmanbomb** [comment]
Pending Squad Division

**Comment by werewolfboy13** [comment]
Would need vetting and making sure team assigned is willing to stick around. PR would need to be handled as needed.
