### ISSUE TITLE
[Bug]: CA Certs Need Compliance

### ISSUE THREAD

**Issue by werewolfboy13** [afocommunity/suggestions#4]
### What Happened?

Cross Bug Report: 

Taken From: https://github.com/werewolfboy13/Spaghetti-Bot/issues/25

This is to fix the improper SSL handling.

CA INTERM CA CERTS

https://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature

Silent Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

An interim CA Cert is needed. 

### Project

AFO BOT 2 (Discord)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by werewolfboy13** [comment]
TEST

**Comment by bombitmanbomb** [comment]
Test Successful

**Comment by bombitmanbomb** [comment]
> the most common reason you would have the kind of problems this module solves is actually due to failing to properly bundle the Intermediate CAs with the server certificate.

**Comment by bombitmanbomb** [comment]
@werewolfboy13 the pem does not have all the required certificates. This module is a hack/workaround

**Comment by werewolfboy13** [comment]
@bombitmanbomb I can get different certs if they are needed in the chain.

**Comment by bombitmanbomb** [comment]
https://www.npmjs.com/package/ssl-root-cas

There's info included in the desc

**Comment by bombitmanbomb** [comment]
inject() is (deprecated)
