### ISSUE TITLE
[Feature]: New BM Command

### ISSUE THREAD

**Issue by xDWRx** [afocommunity/suggestions#40]
### Solution

!SLpass >> Don't make a squad then pass SL to someone to get a kit you want.

### Related Project

Squad Server Plugins

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that there is No promise this feature will be added

**Comment by bombitmanbomb** [comment]
Done

**Comment by bombitmanbomb** [comment]
Added as `!bait`
