### ISSUE TITLE
[Bug]: Users sent a warning while in a squad

### ISSUE THREAD

**Issue by bombitmanbomb** [afocommunity/suggestions#5]
### What Happened?

User List is not properly updated when checking if a user is in a squad, prompting many users to freak out.

### Project

Spaghetti (Squad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by werewolfboy13** [comment]
https://github.com/Thomas-Smyth/SquadJS/pull/193 Was potentally fixed on this draft but was found to not be the case. Also v3.0 may fix this? *Still in dev
