### ISSUE TITLE
[Request]: Plugin: AFONetworkInterface

### ISSUE THREAD

**Issue by bombitmanbomb** [afocommunity/suggestions#6]
### What do you want to see

Strictly a Utility Plugin to facilitate easy communication between Spaghetti and AFO-BOT-2 via Events.

Removes the need for adding API Tokens to every plugin that talks to the server

# Affected Plugins
* AFOTeamkillDisconnect
  - Guts Networking and moves to Event Based System
* AFOTeamkillApology
  - Allow Networking for #7

### Project

Spaghetti (Squad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by werewolfboy13** [comment]
@bombitmanbomb I need more clarification on this

**Comment by bombitmanbomb** [comment]
Don't know how to explain any simpler. Is exactly what it says it is.

**Comment by bombitmanbomb** [comment]
As stated Handles networking between Spaghetti and AFOBOT

**Comment by bombitmanbomb** [comment]
Will be required for any complex networking for systems such as the Seeding plugin or a db linked MapVote. Its an interfacefor AfoBot's api

**Comment by werewolfboy13** [comment]
Moved to approval due to timeout.

**Comment by bombitmanbomb** [comment]
Will work on after #1
