### ISSUE TITLE
[Request]: Plugin: AFOTeamkillApology

### ISSUE THREAD

**Issue by bombitmanbomb** [afocommunity/suggestions#7]
### What do you want to see

# Plan
All teamkills will be indexed for (***__Y__***) Time. Exceeding (***__X__***) Teamkills will result in a Punishment specified (Kick/Ban). This system is to handle users who get (___X___) Teamkills over the course of potentially multiple games

Upon teamkilling, the player as usual is told to apologize in all chat via the Trigger.
> Mistakes Happen sometimes, and the Teamkilling User is not always directly at fault, As such:

On sending a message in chat (_Apology_), The teamkilled User(s) is prompted to Forgive in Squad Chat.
If forgiven, the Relevant teamkill on the player will be removed from the index and not count towards (***__X__***) teamkills in (***__Y__***)  time towards set punishment.

# Notes
* Does not override License Requirements. If a user reaches the Teamkill Threshold set by OWI in a single game, the user will still be removed Regardless of if the user is forgiven or not. This plugin is to handle repeat teamkill offenders over a period of time.
* Players are recommended to **!Forgive** in [__Squad Chat__] to avoid [__All__] spam, But will work in all channels.
* Info is conveyed to the player via RCON Warnings
* To prevent Retaliation, if the user does not apologize, the tked user is not told If they were teamkilled unless the user Apologizes. This mimics Current Behavior, where they find out in chat by the user apologizing. See Apology in Prompt Below to possibly lower retaliation further

# Possible Issues
Abuse
> Potential for Abuse is Very Minimal. At worst a teammate will ignore and Not forgive, Resulting in +1 to the users tracker for Teamkilling. Will result in Intended Behavior.

# Extra Features (Approve Individually)
----
- [ ] Admin Override Command
> Command for users to Force Forgive a user of (___Z___ Argument) Teamkills
> EX: [ChatAdmin] $AdminForgive Trooper 3
* Use Case Example:
  * Blueberries sprinting into Arty
----
- [ ] Apology in Prompt
> Add the Apology message to the Prompt. Not all users have Chat enabled.

EX:

> My bad bro
Type !Forgive in [SquadChat]: (Default Key **L**) to forgive Snow E. (AFO)

* Potential For Abuse
  * Intentionally Teamkilling and sending troll message 
    * Possible Suppression: Log Apologies w/ steam64 and have a basic filter (Obscenities) 
* Length of Send Apology will be limited and cut off if message would exceed the Warning Length Limit.
----

# Affected Plugins
* AFOTeamkillDisconnect
  - Adds Event to clear player TK/DC log to prevent Punishment double up
* AFONetworkInterface
  - Interface via #6
 

### Project

Spaghetti (Squad)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bombitmanbomb** [comment]
Editing reguarding Retaliation Prevention

**Comment by bombitmanbomb** [comment]
Additional Case: If the Teamkilled User Disconnects (Rage Quit) should the killer:
- [ ] Be Automatically Forgiven, Impossible to Apologize
- [ ] Retain +1 TKScore

**Comment by werewolfboy13** [comment]
Denied via board and advisor meeting.
